#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y sysstat tcpdump iputils-ping traceroute strace lsof
      ;;
  esac
}

bootstrap
