#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Ubuntu)
      ${NOSUDO} sudo apt-get install -y sysstat tcpdump iputils-ping traceroute strace lsof dnsutils telnet
      ;;
    Amazon|CentOS)
      ${NOSUDO} sudo yum install -y sysstat tcpdump iputils traceroute strace lsof bind-utils telnet
      ;;
  esac

  pkg ensure misc/figlet
  pkg ensure sysutils/findutils
  pkg ensure parallel/parallel

  pkg ensure sysutils/coreutils
  case "${DISTRIB_ID}" in
    Darwin)
      brew install coreutils
      ;;
  esac
}

bootstrap
