#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  for a in tcpdump ping traceroute lsof figlet; do
    if ! type -P "$a" >/dev/null; then
      return 1
    fi
  done

  return 0
}

main "$@"
